Refactor gen-cloud-init script: improve OS image handling and enhance error checking

diff --git a/bin/inc/gen-cloud-init b/bin/inc/gen-cloud-init
--- a/bin/inc/gen-cloud-init
+++ b/bin/inc/gen-cloud-init
@@ -10,7 +10,8 @@ function gen-cloud-init_help() {
 }
 
 function copy_base_os_image() {
-  local os_image="alpine.img"
+  local os_name="alpine"
+  local os_image="$os_name.img"
 
   local source_dir="${ROOT_DIR}/imgs"
   local source_file="${source_dir}/${os_image}"
@@ -24,7 +25,7 @@ function copy_base_os_image() {
   fi
   cp "$source_file" "${os_image}"
 
-  echo "$os_image"
+  echo "$os_name"
 }
 
 function process_host() {
@@ -33,22 +34,30 @@ function process_host() {
   local default_pass="$3"
   local default_os="$4"
   local default_bridge="$5"
+  local os_name="$6"
   local name=$(echo "$host" | yq '.name')
   local ip=$(echo "$host" | yq '.ip')
 
   echo "Processing host: $name with IP: $ip"
 
   # generate config files for cloud-init to config folder
-  #  - meta-data
-  #  - user-data
-  #  - network-config
+  local config_dir="$name/config"
+  mkdir -p "$config_dir"
+  touch "$config_dir/user-data" "$config_dir/meta-data" "$config_dir/network-config"
+  #  - meta-data.j2
+  #  - user-data.j2
+  #  - $os_name_network-config.j2
 
   # generate iso image with cloud-init config files
-  # rm -f seed.img
-  # genisoimage \
-  #   -output seed.img \
-  #   -volid cidata -rational-rock -joliet \
-  #   user-data meta-data network-config
+  local seed_img="$name/seed.img"
+  # Delete the existing seed image if it exists
+  if [[ -f "${seed_img}" ]]; then
+    rm -f "${seed_img}"
+  fi
+  genisoimage \
+    -output "$seed_img" \
+    -volid cidata -rational-rock -joliet \
+    "$config_dir/user-data" "$config_dir/meta-data" "$config_dir/network-config"
 }
 
 function do_gen-cloud-init() {
@@ -60,17 +69,25 @@ function do_gen-cloud-init() {
     exit 1
   fi
 
+  # check required tools are installed
+  for tool in yq genisoimage; do
+    if ! command -v "$tool" &> /dev/null; then
+      echo "Error: $tool is not installed. Please install it and try again."
+      exit 1
+    fi
+  done
+
   local default_user=$(yq '.defaults.user' vms.yml)
   local default_pass=$(yq '.defaults.pass' vms.yml)
   local default_os=$(yq '.defaults.os' vms.yml)
   local default_bridge=$(yq '.defaults.bridge' vms.yml)
 
-  local os_image=$(copy_base_os_image)
-  echo "Copied OS image: $os_image"
+  local os_name=$(copy_base_os_image)
+  echo "Copied OS image: $os_name.img"
   echo ""
 
   readarray -t hosts < <(yq -o=json -I=0 '.hosts[]' vms.yml)
   for host in "${hosts[@]}"; do
-    process_host "$host" "$default_user" "$default_pass" "$default_os" "$default_bridge"
+    process_host "$host" "$default_user" "$default_pass" "$default_os" "$default_bridge" "$os_name"
   done
 }
